[package]
name = "edix_parser"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "edix_parser"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
edi = { version = "0.2.1", git = "https://github.com/headwayio/edi.git" }
